### ISSUE TITLE
关于 xchoices 的建议

### ISSUE THREAD

**Issue by zepinglee** [xkwxdyy/xchoices#1]
1. 16fad42 的 `xchoices.sty` 会报错：`./xchoices.sty:149: LaTeX cmd Error: Environment 'xchoices' already defined.` 这是因为 latex 中环境 `foo` 其实是由 `\foo` 和 `\endfoo` 两个命令组成的。https://github.com/xkwxdyy/choices-l3/blob/16fad42d7c6c5c216f89a754f68d77160ff5174b/xchoices.sty#L131 已经定义了 `\xchoices`，新定义环境的名就不能再用 `xchioces`。
2. 我个人觉得命名式的 `\xchoices{ \xitem A \xitem B \xitem C }` 用法比较奇怪，可以只保留 `xchoices` 环境。这样也解决了 1。
3. `xchoices` 的内容其实跟 `enumerate` 是一样的，建议使用 `\item` 命令即可，没必要引入额外的命令 `\xitem`。
4. 可以发起个投票看看高中老师们更喜欢 `\choices` 命令还是 `xchoices` 环境。

**Comment by xkwxdyy** [comment]
这方法有效果，具体MWE如下
```tex
\documentclass{article}
\usepackage{graphicx}

\begin{document}
\ExplSyntaxOn
\cs_new:Nn \item:
  {}
\cs_set_eq:NN \item \item:
\cs_new:Npn \__xchoices_env_check_if_figure:nN #1#2
  {
    \str_if_in:nnTF {#1}
      { includegraphics }
      { \bool_set_true:N #2 }
      { 
        \str_if_in:nnTF {#1}
          { includesvg }
          { \bool_set_true:N #2 }
          {}
      }
  }
\cs_new:Npn \__xchoices_env_check_figure_bool:NnN #1#2#3
  % #1: 用于检查的seq
  % #2: 用于检查的内容
  % #3: 输出的figure_bool
  {
    \seq_set_split:Nnn #1 { \item } {#2}
    \seq_remove_all:Nn #1 {}
    \seq_if_empty:NF #1
      {
        \seq_map_inline:Nn #1
          {
            \__xchoices_env_check_if_figure:nN 
              {##1}
              #3
          }
      }
  }
\NewDocumentEnvironment { test } { +b } 
  {}
  {
    \__xchoices_env_check_figure_bool:NnN
      \l_tmpa_seq {#1}
      \l_tmpa_bool
    \bool_if:NTF \l_tmpa_bool {True} {False}
  }
\begin{test}
  \item 111
  \item \includegraphics[width = 2cm]{example-image-a}
\end{test}
\ExplSyntaxOff
\end{document}
```
但是一但加到我的xchoices环境中就报错，编译不了，我在“环境后”参数中加入
```tex
\seq_set_split:Nnn \l__xchoices_env_check_if_figure_seq { \item } {#2}
```
会报错
```bash
*geometry* driver: auto-detecting
*geometry* detected driver: xetex
! Extra }, or forgotten \endgroup.
\endvarwidth ...\@minipagefalse \endgroup \egroup 
                                                  \begingroup \setbox \z@ \v...
l.21     \end{xchoices}
                       
? 
```

**Comment by zepinglee** [comment]
不妨把报错的代码 commit 到一个新的分支然后推送上来，我来看看。

**Comment by xkwxdyy** [comment]
https://github.com/xkwxdyy/xchoices/tree/c4738241e60755c823663fba52bf49da9987196c
已提交

**Comment by zepinglee** [comment]
这种比较适合新建一个 `issue#1` 的分支用于讨论。`dev` 最好保持能编译通过的状态。

**Comment by xkwxdyy** [comment]
好的，https://github.com/xkwxdyy/xchoices/tree/issue1
已新建

**Comment by zepinglee** [comment]
这个 bug 比较麻烦……

**Comment by xkwxdyy** [comment]
真解决不了就只能按照现在的方式，通过`mode = text`，`mode = figure`手动切换了

**Comment by xkwxdyy** [comment]
> LaTeX2e 需要用 `\@ifstar`，LaTeX3 可以用 `\peek_meaning_remove:NTF`，举个例子：
> 
> ```
> \documentclass{article}
> \usepackage{expl3}
> \ExplSyntaxOn
> \cs_new:Npn \test
>   {
>     \peek_meaning_remove:NTF *
>       { true }
>       { false }
>   }
> \ExplSyntaxOff
> \begin{document}
> \test foo
> \test* bar
> \end{document}
> ```

这个方法如果只使用`xchoices`环境可以，但是如果嵌套在`enumerate`环境里会报错，需要使用下面的Renew方法
