### ISSUE TITLE
基线对齐问题

### ISSUE THREAD

**Issue by zepinglee** [xkwxdyy/xchoices#2]
我是在 411630b 上测试的：

```latex
\documentclass{article}
\usepackage{xchoices}
\begin{document}

\begin{xchoices}[label-style = Roman]
  \item Lorem ipsum.
  \item norem opsum.
\end{xchoices}

\begin{xchoices}[label-style = Roman, label-pos = left-top]
  \item Lorem ipsum.
  \item norem opsum.
\end{xchoices}

\end{document}
```

1. 标签的默认位置是 `label-pos = left`（或者 `anchor = west`）。但是这会导致标签和选项内容的基线没有对齐，像“norem opsum” 没有升部就会特别明显。而且不同选项的基线也没对齐。
<img width="384" alt="Screen Shot 2022-01-31 at 18 32 33" src="https://user-images.githubusercontent.com/12290822/151778204-aa686c18-7902-40e1-bc3d-2270fa8ab307.png">

2. 如果设置 `label-pos = left-top`，同样基线没有对齐。
<img width="393" alt="Screen Shot 2022-01-31 at 18 33 30" src="https://user-images.githubusercontent.com/12290822/151778334-c058eab8-24b7-4a7a-a108-44a5597848c5.png">

感觉 `coffin` 不太适合处理这个问题。它直接将 coffin 的 pole 对齐，还没有考虑内部的文字位置，这样处理太机械了。可能 2e 的 `\parbox` 和 `minipage` 更合适。

**Comment by xkwxdyy** [comment]
> 感觉 coffin 不太适合处理这个问题。它直接将 coffin 的 pole 对齐，还没有考虑内部的文字位置，这样处理太机械了。可能 2e 的 \parbox 和 minipage 更合适。

`coffin`已经是我想到的最优解了
- anchor的不同设置就是基于`coffin`的拼接才实现，我知道的其他方式很难做到这么精细的对齐和调整
- 在储存到`box`的时候，我使用了`varwidth`环境
```tex
\hbox_set:cw { l__xchoices_env_ \int_to_roman:n { \l__xchoices_env_xitem_int } _box }
      \begin{varwidth}{\hsize}
...
      \end{varwidth}
\hbox_set_end:
```
`varwidth`也是基于`minipage`的，我刚试着去掉了，换成了`minipage`但好像也还是一样的效果

**Comment by zepinglee** [comment]
> * anchor的不同设置就是基于`coffin`的拼接才实现，我知道的其他方式很难做到这么精细的对齐和调整

`\parbox` 的一个 optional argument 可以设置与外部（标签）的对齐方式，具体参考 lshort-zh-cn。

**Comment by xkwxdyy** [comment]
但是`parbox`的参数输入决定了在此处用不了，否则实现不了`item`的效果

**Comment by xkwxdyy** [comment]
> > * anchor的不同设置就是基于`coffin`的拼接才实现，我知道的其他方式很难做到这么精细的对齐和调整
> 
> `\parbox` 的一个 optional argument 可以设置与外部（标签）的对齐方式，具体参考 lshort-zh-cn。

`varwidth`其实也可以设置外部对齐方式，和`minipage`, `parbox`一样，因为好像是基于`minipage`写的

**Comment by xkwxdyy** [comment]
如果能根据内容获得需要升降的内容就好了，因为可以在把`box`传到`seq`之前进行升降

**Comment by zepinglee** [comment]
我试试能不能只依赖 `expl3` + `xparse` + `\parbox` 或 `minipage` 实现。 毕竟 `varwidth` 不是核心宏包，应尽量避免依赖它。

**Comment by xkwxdyy** [comment]
我用`varwidth`是用`\hsize`来获得它的“最小宽度”，如果用`minipage`的话无法有这个效果，我不知道如何解决这个问题

**Comment by xkwxdyy** [comment]
经测试原来的实现方式可以不需要`varwidth`环境，但是对齐方式仍没有解决

**Comment by zepinglee** [comment]
我参考了 https://github.com/cgnieder/tasks/blob/303ff1dcd1eec81437e4ccbef5eb26e9b070f3d4/tasks.sty#L310-L365 的处理方法，可以用 `vcoffin` 替代 `varwidth`，然后在外面嵌套一层 `hcoffin`。其中 `vcoffin` 可以使用 `T` 和 `B` 分别按照首行和末行的基线对齐，`hcoffin` 的  `T`/`B` 跟 `H` 是一样的，都是按照基线对齐。另外可以用 `\strut` 将末行撑高一些，防止整体跟下文的段落过于接近。

```latex
\documentclass{article}

\usepackage{expl3}
\usepackage{xcoffins}
\usepackage{lipsum}

\begin{document}

\ExplSyntaxOn
\coffin_new:N \l__a_coffin
\coffin_new:N \l__b_coffin
\coffin_new:N \l__tmp_coffin

\hcoffin_set:Nn \l__a_coffin
  {
    \vcoffin_set:Nnn \l__tmp_coffin { 6em }
      {
        \noindent \strut
        norem~ opsum \newline
        Lorem~ ipsum \strut
      }
    \coffin_mark_handle:Nnnn \l__tmp_coffin {r} {H} {red}
    \coffin_mark_handle:Nnnn \l__tmp_coffin {r} {T} {green}
    \coffin_mark_handle:Nnnn \l__tmp_coffin {r} {B} {blue}
    \coffin_typeset:Nnnnn \l__tmp_coffin {l} {T} {0pt} {0pt}
  }
\hcoffin_set:Nn \l__b_coffin
  {
    \vcoffin_set:Nnn \l__tmp_coffin { 6em }
      {
        \noindent \strut
        Lorem~ ipsum \newline
        Lorem~ ipsum \strut
      }
    \coffin_typeset:Nnnnn \l__tmp_coffin {l} {T} {0pt} {0pt}
  }

\coffin_join:NnnNnnnn \l__a_coffin {r} {H} \l__b_coffin {l} {H} {0pt} {0pt}

\lipsum[1]\par
Lipsum~ \coffin_typeset:Nnnnn \l__a_coffin {l} {H} {0pt} {0pt} \par
\lipsum[1]\par

\ExplSyntaxOff

\end{document}
```

**Comment by zepinglee** [comment]
> 我用`varwidth`是用`\hsize`来获得它的“最小宽度”，如果用`minipage`的话无法有这个效果，我不知道如何解决这个问题

也可以先将每个选项的内容装进 `hbox` 中获得自然宽度，然后根据版心和列数要求算出选项最终的宽度，以这个宽度作为 `vcoffin` 的固定宽度，跟 `\parbox` 和 `minipage` 类似，而且更方便对齐。

**Comment by xkwxdyy** [comment]
> > 我用`varwidth`是用`\hsize`来获得它的“最小宽度”，如果用`minipage`的话无法有这个效果，我不知道如何解决这个问题
> 
> 也可以先将每个选项的内容装进 `hbox` 中获得自然宽度，然后根据版心和列数要求算出选项最终的宽度，以这个宽度作为 `vcoffin` 的固定宽度，跟 `\parbox` 和 `minipage` 类似，而且更方便对齐。

这样的话每个选项的宽度是一样的了？

**Comment by xkwxdyy** [comment]
可我的`\item `只能把内容存到一个里面，要么是`box`要么是`coffin`，这怎么处理呢

**Comment by zepinglee** [comment]
> 这样的话每个选项的宽度是一样的了？

对。

**Comment by zepinglee** [comment]
> 可我的`\item `只能把内容存到一个里面，要么是`box`要么是`coffin`，这怎么处理呢

`\seq_set_split:Nnn` 后每个选项的内容是以 tl 的形式存在 seq 中的，可以分别存到 `box` 和 `coffin`。

**Comment by xkwxdyy** [comment]
但我内容都没有怎么获得列数呢？ 原本的做法是先获得内容再去计算宽度判断

**Comment by xkwxdyy** [comment]
我一直没弄懂`h-*`和`v-*`比如`box`, `coffin`的区别

**Comment by zepinglee** [comment]
> 但我内容都没有怎么获得列数呢？ 原本的做法是先获得内容再去计算宽度判断

先从 seq 读取内容放进 hbox 计算宽度和列数，再从  seq 读取一遍内容放进 coffin 用于输出。

**Comment by zepinglee** [comment]
> 我一直没弄懂`h-*`和`v-*`比如`box`, `coffin`的区别

其实我也没有完全搞懂底层 h 和 v 的区别，需要阅读 texbook。

**Comment by xkwxdyy** [comment]
https://github.com/xkwxdyy/xchoices/commit/6f1b6b04408aed2434182391b6748a2117506607
尝试用vcoffin处理，但是失败了

**Comment by xkwxdyy** [comment]
```tex
\cs_new:cpn { __xchoices_label_pos_set_left:NN } #1#2
  {
    \coffin_join:NnnNnnnn
      #1 { H } { r }
      #2 { H } { l }
      { 5pt + \l__xchoices_coffin_join_horizontal_sep_dim }
      { \l__xchoices_coffin_join_vertical_sep_dim }
...
```
把`left`的`join`的垂直基线改掉就可以了，但是带来的结果就是图片会变成`left-bottom`，这个如何处理
![image](https://user-images.githubusercontent.com/87134063/151917661-46fb0f85-db14-47b2-91d1-c81f7a5a6443.png)

**Comment by xkwxdyy** [comment]
调用了`graphbox`宏包的`align`选项解决，不过需要用户手动添加
```tex
\begin{xchoices}
  \item testtest
  \item* \includegraphics[width = 2cm, align = c]{example-image-a}
  \item testtesttesttesttest
  \item* testtesttesttesttesttestte
  \item testtesttesttesttesttesttesttes
\end{xchoices}
```
![image](https://user-images.githubusercontent.com/87134063/151918592-ef41aeae-dfea-47c7-b2af-d4625fd01c61.png)

**Comment by zepinglee** [comment]
> 调用了`graphbox`宏包的`align`选项解决，不过需要用户手动添加

我感觉可以在存入 `hbox` 后判断高度，如果超过 `2\baselineskip`，在 `vcoffin` 这一步就用 `\coffin_set_vertical_pole` 较正一下 `T` 的位置。

**Comment by xkwxdyy** [comment]
经测试用`\baselineskip`可以检测最小的图片是`1cm`高（在不设置行距等情况下）
```tex
\documentclass{ctexart}
\usepackage{xchoices}
\usepackage{graphbox}

% 统一控制答案的显示
\xchoicesetup{
  showanswer
}
\begin{document}
  \begin{enumerate}
    \item 
      2020 年 3 月 14 日是全球首个国际圆周率日 ( $\pi$ Day). 历史上, 求圆周率 $\pi$ 的方法有多种, 与中国传统数学中的 “割圆术”相似. 数学家阿尔. 卡西的方 法是: 当正整数 $n$ 充分大时, 计算单位圆的内接正 $6 n$ 边形的周长和外切 正 $6 n$ 边形 (各边均与圆相切的正 $6 n$ 边形) 的周长, 将它们的算术平均数 作为 $2 \pi$ 的近似值. 按照阿尔. 卡西的方法, $\pi$ 的近似值的表达式是 \xparen
        \begin{xchoices}
          \item testtest
          \item* \includegraphics[height = 10mm]{example-image-a}
          \item testtesttesttesttest
          \item* testtesttesttesttesttestte
          \item testtesttesttesttesttesttesttes
        \end{xchoices}
    \item
      2020 年 3 月 14 日是全球首个国际圆周率日 ( $\pi$ Day). 历史上, 求圆周率 $\pi$ 的方法有多种, 与中国传统数学中的 “割圆术”相似. 数学家阿尔. 卡西的方 法是: 当正整数 $n$ 充分大时, 计算单位圆的内接正 $6 n$ 边形的周长和外切 正 $6 n$ 边形 (各边均与圆相切的正 $6 n$ 边形) 的周长, 将它们的算术平均数 作为 $2 \pi$ 的近似值. 按照阿尔. 卡西的方法, $\pi$ 的近似值的表达式是 \xparen
        \begin{xchoices}[showanswer = false]
          \item 选项1
          \item* 选项2
          \item 选项3
          \item* 选项4
        \end{xchoices}
  \end{enumerate}

  \begin{xchoices}[label-style = alph]
    \item \textbf{ \huge norem opsum}
    \item Lipnorem opsum
  \end{xchoices}
\end{document}
```
![image](https://user-images.githubusercontent.com/87134063/151923499-c67ad480-dc2c-46ee-8ab7-f02c8e8b9d0c.png)
而且把字放大后，字依旧是基线对齐，基本解决问题

**Comment by xkwxdyy** [comment]
b47b66f5e62e048c7b304c6727623bd8fb63242d
感谢李老师，我自己测试情况是问题解决了
