### ISSUE TITLE
较长选项内容的换行问题

### ISSUE THREAD

**Issue by zepinglee** [xkwxdyy/xchoices#3]
```latex
\documentclass{article}

\usepackage{xchoices}
\usepackage{lipsum}

\begin{document}

\lipsum[1]

\begin{enumerate}
  \item Lorem ipsum.
    \begin{xchoices}
      \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
        Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis.
      \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
    \end{xchoices}
\end{enumerate}

\begin{xchoices}
  \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
    Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis.
  \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
\end{xchoices}

\lipsum[1]

\end{document}
```

5151101 中似乎无法自动换行。
<img width="673" alt="Screen Shot 2022-02-01 at 21 22 05" src="https://user-images.githubusercontent.com/12290822/151976133-d6c02da5-2908-458b-acf0-cedb0b250f5a.png">

相同的代码在 0dfaeec （合并 issue2 分支前）中可以自动换行，但是会超出右侧版心。似乎是总宽度的计算有误。
<img width="620" alt="Screen Shot 2022-02-01 at 21 22 39" src="https://user-images.githubusercontent.com/12290822/151976208-2d201bb9-da75-4a15-ae5f-2eafc37b680a.png">

**Comment by xkwxdyy** [comment]
不是总宽度计算有误，是因为使用了
```tex
\begin{varwidth}{\hsize}
   ...
\end{varwidth}
```
其中`\hsize`获取了内容的自然宽度，所以
```tex
\begin{enumerate}
  \item Lorem ipsum.
    \begin{xchoices}
      \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
        Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis.
      \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
    \end{xchoices}
\end{enumerate}
Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
        Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis.
```
会得到：

![image](https://user-images.githubusercontent.com/87134063/151979308-bb710e3b-f51e-4c94-85bf-f48ea1cd4edf.png)

**Comment by xkwxdyy** [comment]
因为issue2之后把`varwidth`去掉了，现在重新加回来调整一下宽度为：
```tex
\begin{varwidth}[t]{ \dim_eval:n{\hsize - 1.1\textwidth + \linewidth} }
```
即可
![image](https://user-images.githubusercontent.com/87134063/151981795-b1554b46-5c36-47a6-a8e3-e2854c67a1df.png)

**Comment by xkwxdyy** [comment]
已修复
ad695689ed11484eaa570cb9ecacb64d80132dd8

**Comment by zepinglee** [comment]
> 其中`\hsize`获取了内容的自然宽度，所以

我不太明白这句话。`\hsize` 是用于底层 TeX 控制的参数，应该跟内容无关。而且“自然宽度”一般说的是内容在不换行情况下的宽度。下面是个实验，其中为了区分 `\textwidth` 和 `\linewidth` 使用了 `twocolumn` 参数进行双栏排版。
```latex
\documentclass[twocolumn]{article}
\begin{document}
\the\textwidth\par
\the\linewidth\par
\the\hsize\par
\begin{enumerate}
  \item \the\textwidth
  \item \the\linewidth
  \item \the\hsize
  \item
    \begin{enumerate}
      \item \the\textwidth
      \item \the\linewidth
      \item \the\hsize
      \item
        \begin{enumerate}
          \item \the\textwidth
          \item \the\linewidth
          \item \the\hsize
        \end{enumerate}
    \end{enumerate}
\end{enumerate}
\end{document}
```
结果：
<img width="187" alt="Screen Shot 2022-02-01 at 23 01 36" src="https://user-images.githubusercontent.com/12290822/151993168-2afc97d7-3d22-451b-bc51-4774d34703f3.png">

可以看到 `\textwidth` 始终是页面版心的宽度；`\linewidth` 会随 `enumerate` 层级的增加而变化；`\hsize` 在以上几种情况中都是 `\linewidth` 的初始值。

**Comment by xkwxdyy** [comment]
可能是我误解了（
因为我知道`\hsize`命令是通过一个`varwidth`环境的使用才知道的
效果就是使得小页环境宽度是内容的宽度而不用手段输入，所以我可能就误认为了

**Comment by zepinglee** [comment]
> 因为issue2之后把`varwidth`去掉了，现在重新加回来调整一下宽度为：
> 
> ```
> \begin{varwidth}[t]{ \dim_eval:n{\hsize - 1.1\textwidth + \linewidth} }
> ```

我没太看懂这样为何可以修改正确，尤其是 1.1 这个参数是怎么来的？而且在双栏的情况下，`\dim_eval:n{\hsize - 1.1\textwidth + \linewidth` 是负的。 ad69568 在下面的测试中会出问题。
```latex
\documentclass[twocolumn]{article}
\usepackage{xchoices}
\usepackage{lipsum}
\begin{document}
\lipsum[1]

\begin{enumerate}
  \item Lorem ipsum.
    \begin{xchoices}
      \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
        Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis.
      \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
    \end{xchoices}
\end{enumerate}

\begin{xchoices}
  \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
    Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis.
  \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
\end{xchoices}

\lipsum[1]

\end{document}
```
<img width="708" alt="Screen Shot 2022-02-01 at 23 15 34" src="https://user-images.githubusercontent.com/12290822/151995755-cbd3c86f-dedd-493c-8118-45e51a13b297.png">

**Comment by xkwxdyy** [comment]
因为如果没有1.1的话当时虽然宽度溢出的效果会改善，但是还是不明显，所以想着要多减掉一点
其实应该还多的宽度是`enumerate`的`label`宽度，但是这个不知如何处理
只是`-\textwidth + \linewidth`的话是不够的，但是又不能把`enumerate`的参数加进去
其实只是一个投机取巧的做法，我并没有真正解决。。

**Comment by zepinglee** [comment]
> 因为如果没有1.1的话当时虽然宽度溢出的效果会改善，但是还是不明显，所以想着要多减掉一点 其实应该还多的宽度是`enumerate`的`label`宽度，但是这个不知如何处理 只是`-\textwidth + \linewidth`的话是不够的，但是又不能把`enumerate`的参数加进去 其实只是一个投机取巧的做法，我并没有真正解决。。

那这个 1.1 是调出来的？（怎么感觉跟神经网络调参一样）

**Comment by xkwxdyy** [comment]
我以为没戏了 调了个1.2 ，发现可行，但多了，调成1.1，zepinglee上面那个例子还就刚刚好，效果很到位（

**Comment by xkwxdyy** [comment]
其实把`\linewidth`改成0.9倍的也行，但是双栏的却是也会出现那个问题

**Comment by xkwxdyy** [comment]
这么看的话`\textwidth`换成单栏宽度应该可以

**Comment by xkwxdyy** [comment]
经过测试改为
```tex
      \begin{varwidth}[t]{ \dim_eval:n{\hsize - \columnwidth + 0.9\linewidth} }
```
解决：
![image](https://user-images.githubusercontent.com/87134063/152004531-f9ff3134-bc79-4f73-8ebc-a7fffac07b0a.png)

**Comment by zepinglee** [comment]
这个地方的宽度应该是要准确算出来的，如果是调了一个 0.9 的参数就总会有些 cormer case 出现问题。

我正在阅读你的代码，不过还没完全理清你的思路。

**Comment by xkwxdyy** [comment]
> 这个地方的宽度应该是要准确算出来的，如果是调了一个 0.9 的参数就总会有些 cormer case 出现问题。
> 
> 我正在阅读你的代码，不过还没完全理清你的思路。

主要是https://github.com/xkwxdyy/xchoices/blob/ad695689ed11484eaa570cb9ecacb64d80132dd8/xchoices.sty#L1309-#L1379
这个地方是关键代码

**Comment by xkwxdyy** [comment]
两个`\item`之间“夹住”内容存到seq之前，先用varwidth环境包住（解决换行问题）

**Comment by xkwxdyy** [comment]
> 这个地方的宽度应该是要准确算出来的，如果是调了一个 0.9 的参数就总会有些 cormer case 出现问题。
> 
> 我正在阅读你的代码，不过还没完全理清你的思路。

精确 算出来能做到吗？因为这个和当前的环境有关，如果嵌套在`enumerate`里面的话还有前面的label宽度，如果在正文里就没有这一段

**Comment by xkwxdyy** [comment]
```tex
      \begin{varwidth}[t]{ \dim_eval:n{ \hsize - \columnwidth + \linewidth - \leftmargin } }
```
去掉一个`\leftmargin`后基本能正常了
![image](https://user-images.githubusercontent.com/87134063/152009064-5fbea3f7-1c38-4ab1-a05c-eec105ff5ea6.png)

**Comment by xkwxdyy** [comment]
> ```
>       \begin{varwidth}[t]{ \dim_eval:n{ \hsize - \columnwidth + \linewidth - \leftmargin } }
> ```
> 
> 去掉一个`\leftmargin`后基本能正常了 ![image](https://user-images.githubusercontent.com/87134063/152009064-5fbea3f7-1c38-4ab1-a05c-eec105ff5ea6.png)

但是改变了paperwidth后又出问题了，还是等李老师的解决吧，我能力不够了（orz

**Comment by zepinglee** [comment]
> 精确 算出来能做到吗？因为这个和当前的环境有关，如果嵌套在`enumerate`里面的话还有前面的label宽度，如果在正文里就没有这一段

应该是可以的。`enumerate` 中的 `\linewidth` 已经减去了前面的标签（其实是 `\leftmargin` + `\rightmargin`），参考 `enumitem` 文档的这个图。
<img width="538" alt="Screen Shot 2022-02-02 at 00 35 52" src="https://user-images.githubusercontent.com/12290822/152010263-e5929690-36b2-403b-ba77-d080b07f52d0.png">

所以，你的 `varwidth` 环境的参数应该是 `\linewidth`，减去 `choices` 环境的标签宽度和 sep。

**Comment by xkwxdyy** [comment]
> 所以，你的 varwidth 环境的参数应该是 \linewidth，减去 choices 环境的标签宽度和 sep

`sep`是指？

**Comment by xkwxdyy** [comment]
基本实现了
```tex
\cs_new:Nn \__xchoices_env_xitem_new:
  {
    % 如果是第一项的话就不需要\__xchoices_env_xitem_out:
    % 只有第二项开始才需要处理上一个
    \int_compare:nNnF { \l__xchoices_env_xitem_int } = { 0 }
      { \__xchoices_env_xitem_out: }
    % xitem计数器的值+1
    \int_incr:N \l__xchoices_env_xitem_int
    % 测试一下是否存在了对应值的box，不存在的话新声明一个
    \box_if_exist:cF { l__xchoices_env_ \int_to_roman:n { \l__xchoices_env_xitem_int } _box }
      {
        \box_new:c { l__xchoices_env_ \int_to_roman:n { \l__xchoices_env_xitem_int } _box }
      }
    \bool_if_exist:cF { l__xchoices_env_ \int_to_roman:n { \l__xchoices_env_xitem_int } _bool}
      {
        \bool_new:c { l__xchoices_env_ \int_to_roman:n { \l__xchoices_env_xitem_int } _bool }
      }
    \coffin_if_exist:cF
      { l__xchoices_coffin_label_ \int_to_roman:n { \l__xchoices_env_xitem_int } _coffin }
      {
        \coffin_new:c { l__xchoices_coffin_label_ \int_to_roman:n { \l__xchoices_env_xitem_int } _coffin }
      }
    \vcoffin_set:Nnn \l__xchoices_tmp_coffin {1em}
      {
        \l__xchoices_prelabel_tl
        \__xchoices_current_label_transform_int:n { \int_use:N \l__xchoices_env_xitem_int }
        \l__xchoices_postlabel_tl
      }
    \hcoffin_set:cn { l__xchoices_coffin_label_ \int_to_roman:n { \l__xchoices_env_xitem_int } _coffin }
      {
        \l__xchoices_prelabel_tl
        \__xchoices_current_label_transform_int:n { \int_use:N \l__xchoices_env_xitem_int }
        \l__xchoices_postlabel_tl
      }
    % 存 label的宽度
    \dim_if_exist:cF
      { l__xchoices_label_width_ \int_to_roman:n { \l__xchoices_env_xitem_int } _dim}
      {
        % 不存在的话就新定义
        \dim_new:c { l__xchoices_label_width_ \int_to_roman:n { \l__xchoices_env_xitem_int  } _dim }
      }
    \dim_set:cn { l__xchoices_label_width_ \int_to_roman:n { \l__xchoices_env_xitem_int  } _dim }
      {
        \coffin_wd:c { l__xchoices_coffin_label_ \int_to_roman:n { \l__xchoices_env_xitem_int } _coffin }
      }
    % 将错误答案对应项数的bool设置为false
    \bool_set_false:c { l__xchoices_env_ \int_to_roman:n { \l__xchoices_env_xitem_int } _bool}
    \hbox_set:cw { l__xchoices_env_ \int_to_roman:n { \l__xchoices_env_xitem_int } _box }
      % \begin{varwidth}[t]{\hsize}
      \begin{varwidth}[t]{ \dim_eval:n{ \linewidth - \use:c { l__xchoices_label_width_ \int_to_roman:n { \l__xchoices_env_xitem_int  } _dim } - \leftmargin } }
  }
```
![image](https://user-images.githubusercontent.com/87134063/152015190-30198cdb-a44c-49e5-9583-a3aa53a285a4.png)

经过测试，修改paperwidth都有效果

**Comment by xkwxdyy** [comment]
这次应该解决了
67e83a6d9d7fa10c8e3c0a98df8e30319dbd5bb2

**Comment by zepinglee** [comment]
> > 所以，你的 varwidth 环境的参数应该是 \linewidth，减去 choices 环境的标签宽度和 sep
> 
> `sep`是指？

“A.” 到右侧内容之间的距离，类似 `enumitem` 那张图的 `labelsep`。

**Comment by xkwxdyy** [comment]
> > > 所以，你的 varwidth 环境的参数应该是 \linewidth，减去 choices 环境的标签宽度和 sep
> > 
> > 
> > `sep`是指？
> 
> “A.” 到右侧内容之间的距离，类似 `enumitem` 那张图的 `labelsep`。

已继续优化
2e2e6e2e074612e4efd35793e02baae10ea350df

**Comment by zepinglee** [comment]
我试了一下
```latex
\documentclass{article}
\usepackage{geometry}
\usepackage{lipsum}
\usepackage{xchoices}

\geometry{showframe}

\begin{document}
\begin{enumerate}
  \item \lipsum[1]
    \begin{xchoices}
      \item \lipsum[1]
    \end{xchoices}
  \item \lipsum[1]
\end{enumerate}
\end{document}
```
<img width="611" alt="Screen Shot 2022-02-02 at 02 10 53" src="https://user-images.githubusercontent.com/12290822/152026138-e96d8679-a36b-41eb-8c18-e5af5ce1b96c.png">

基本上看不到溢出，只是有两个警告：
```
Overfull \hbox (0.28pt too wide) in paragraph at lines 12--12
[]\TU/lmr/m/n/10 A. 

Overfull \hbox (0.28pt too wide) in paragraph at lines 16--16
[]\TU/lmr/m/n/10 A. 
```
应该是标签“A.”的盒子溢出了。总体不影响使用。

**Comment by xkwxdyy** [comment]
感谢zepinglee指导

**Comment by zepinglee** [comment]
> 所以，你的 `varwidth` 环境的参数应该是 `\linewidth`，减去 `choices` 环境的标签宽度和 sep。

我这里说的不太对，应该是 `\linewidth` 减去下图中“amet”与“Lorem”两词左侧的水平相对距离。
<img width="294" alt="Screen Shot 2022-02-02 at 14 08 19" src="https://user-images.githubusercontent.com/12290822/152101829-b2b604f0-2160-4b90-bd42-b0cb976654a9.png">

目前宏包中的设置是 https://github.com/xkwxdyy/xchoices/blob/2e2e6e2e074612e4efd35793e02baae10ea350df/xchoices.sty#L1368

我感觉不应该这么计算，因为传给 `varwidth` 时 `\leftmargin` 是所在 `enumerate` 层级的 `\leftmargin`，也就是 "amet" 到左侧版心边缘的距离。

**Comment by zepinglee** [comment]
选项左侧对齐问题在 #4 中继续讨论。
