### ISSUE TITLE
选项左侧对齐问题

### ISSUE THREAD

**Issue by zepinglee** [xkwxdyy/xchoices#4]
自 #3 继续。

> 所以，你的 `varwidth` 环境的参数应该是 `\linewidth`，减去 `choices` 环境的标签宽度和 sep。

我这里说的不太对，应该是 `\linewidth` 减去下图中“amet”与“Lorem”两词左侧的水平相对距离。
<img width="294" alt="Screen Shot 2022-02-02 at 14 08 19" src="https://user-images.githubusercontent.com/12290822/152101829-b2b604f0-2160-4b90-bd42-b0cb976654a9.png">

目前宏包中的设置是 https://github.com/xkwxdyy/xchoices/blob/2e2e6e2e074612e4efd35793e02baae10ea350df/xchoices.sty#L1368

我感觉不应该这么计算，因为传给 `varwidth` 时 `\leftmargin` 是所在 `enumerate` 层级的 `\leftmargin`，也就是 "amet" 到左侧版心边缘的距离。

_Originally posted by @zepinglee in https://github.com/xkwxdyy/xchoices/issues/3#issuecomment-1027624026_

**Comment by zepinglee** [comment]
另外国内高考试卷的选项标签一般是紧贴左侧边缘的，比如下图的“A.”跟“若”对齐（所以我一开始会说“减去 label width 和 label sep”）。
<img width="729" alt="Screen Shot 2022-02-02 at 14 21 12" src="https://user-images.githubusercontent.com/12290822/152104260-0604e9b3-2497-4197-83c8-2cd0a04a4dbf.png">

所以在调用 hlist 时还需要调整一下 `left margin` 和 `item offset` 的值。（下图是 hlist 的文档）
<img width="695" alt="Screen Shot 2022-02-02 at 14 31 23" src="https://user-images.githubusercontent.com/12290822/152105258-e46791ad-2d99-4446-91e7-cf82cafc1523.png">

**Comment by zepinglee** [comment]
吐槽一下 `hlist` 宏包：文档没有英文；设置的 key 中居然带空格，而且跟 LaTeX 2e kernel 的差异很大（尤其是 `left margin` 和 `item offset`）。

`enumitem` 文档的这个图描述了 2e kernel 的控制参数，而且 `enumitem` 设置的键值名字也是对应的，比如 `leftmargin` 和 `itemindent`（虽然“现代”一些的宏包的更倾向于用“-”分隔开）。
<img width="551" alt="Screen Shot 2022-02-02 at 14 45 09" src="https://user-images.githubusercontent.com/12290822/152106597-648f990e-ca5b-4ca9-bb92-e514ef3e6ee5.png">

我打算重新实现一个 `choices` 环境，只依赖 `expl3`, `xparse`, `xcoffins`，不依赖 `hlist` 和 `varwidth`。

**Comment by xkwxdyy** [comment]
我的实现原理其实是用了`hlist`来处理，但是取消了label，而是“手动”把label放进coffin，hlist只是用来方便地控制每行的对齐和每行的个数，把`item offset`设置为`0pt`即可对齐
![image](https://user-images.githubusercontent.com/87134063/152160121-ca1d4a1b-0459-456e-8f28-35611c286898.png)

**Comment by xkwxdyy** [comment]
60c37f8f197c01004630367e85d3d64268594fb5
已解决

**Comment by zepinglee** [comment]
1703281 中选项的宽度显得有些小了。

```latex
\documentclass{article}
\usepackage{geometry}
\usepackage{lipsum}
\usepackage{xchoices}

\geometry{showframe}

\begin{document}
item \lipsum[1]\par
\begin{enumerate}
  \item \lipsum[1]
    \begin{xchoices}
      \item \lipsum[1]
    \end{xchoices}
  \item \lipsum[1]
\end{enumerate}
\end{document}
```

<img width="679" alt="Screen Shot 2022-02-02 at 22 51 37" src="https://user-images.githubusercontent.com/12290822/152177494-839fbaaf-4fa9-422b-9fd9-19549120e8c9.png">

**Comment by xkwxdyy** [comment]
> 1703281 中选项的宽度显得有些小了。

7bf0dd5aa471edbdd54a0c2fe9009593338d2367
已修复

**Comment by zepinglee** [comment]
<img width="696" alt="Screen Shot 2022-02-03 at 10 56 36" src="https://user-images.githubusercontent.com/12290822/152275851-40ac54b1-aac8-413d-a553-271f26e159f8.png">

这个右边又溢出了。

**Comment by xkwxdyy** [comment]
我找到原因了，在最后一步的时候有些小问题，MWE如下
```tex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
\dim_new:N \l__xchoices_coffin_join_horizontal_sep_dim
\str_new:N \l__xchoices_coffin_current_label_pos_str
\str_set:Nn \l__xchoices_coffin_current_label_pos_str {left}
\cs_new:Npn \__xchoices_label_hsep_init:N #1
  {
    \dim_set:Nn \l__xchoices_coffin_join_horizontal_sep_dim
      {
        \str_if_in:NnTF #1 {left}
          { 5pt }
          {
            \str_if_in:NnTF #1 {right}
              {-5pt}
              {0pt}
          }
      }
  }
\__xchoices_label_hsep_init:N
  \l__xchoices_coffin_current_label_pos_str
% \dim_use:N \l__xchoices_coffin_join_horizontal_sep_dim
\ExplSyntaxOff
\end{document}
```
下面是报错，我想不通这个哪里有问题
![image](https://user-images.githubusercontent.com/87134063/152284350-806b7193-89c1-4673-9984-bacd37d811ee.png)

**Comment by xkwxdyy** [comment]
> 我找到原因了，在最后一步的时候有些小问题，MWE如下
> 
> ```
> \documentclass{article}
> 
> \begin{document}
> \ExplSyntaxOn
> \dim_new:N \l__xchoices_coffin_join_horizontal_sep_dim
> \str_new:N \l__xchoices_coffin_current_label_pos_str
> \str_set:Nn \l__xchoices_coffin_current_label_pos_str {left}
> \cs_new:Npn \__xchoices_label_hsep_init:N #1
>   {
>     \dim_set:Nn \l__xchoices_coffin_join_horizontal_sep_dim
>       {
>         \str_if_in:NnTF #1 {left}
>           { 5pt }
>           {
>             \str_if_in:NnTF #1 {right}
>               {-5pt}
>               {0pt}
>           }
>       }
>   }
> \__xchoices_label_hsep_init:N
>   \l__xchoices_coffin_current_label_pos_str
> % \dim_use:N \l__xchoices_coffin_join_horizontal_sep_dim
> \ExplSyntaxOff
> \end{document}
> ```
> 
> 下面是报错，我想不通这个哪里有问题 ![image](https://user-images.githubusercontent.com/87134063/152284350-806b7193-89c1-4673-9984-bacd37d811ee.png)

通过`tl`过渡好像可以解决，(感觉`str`的结果语句如果是文本的话会变成`str`，但是应该也不是这样，我用`$x^2$`输出正确，很奇怪)
下面是MWE：
```tex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\dim_new:N \l__xchoices_coffin_join_horizontal_sep_dim
\str_new:N \l__xchoices_coffin_current_label_pos_str
\str_set:Nn \l__xchoices_coffin_current_label_pos_str {left}
\tl_new:N \l__xchoices_label_hsep_init_tl
\cs_generate_variant:Nn \dim_set:Nn {NV}
\cs_new:Npn \__xchoices_label_hsep_init:N #1
  {
    \str_if_in:NnTF #1 {left}
      {
        \tl_set:Nn \l__xchoices_label_hsep_init_tl {5pt}
      }
      {
        \str_if_in:NnTF #1 {right}
          {
            \tl_set:Nn \l__xchoices_label_hsep_init_tl {-5pt}
          }
          {
            \tl_set:Nn \l__xchoices_label_hsep_init_tl {0pt}
          }
      }
    % \tl_use:N \l__xchoices_label_hsep_init_tl
    \dim_set:NV
      \l__xchoices_coffin_join_horizontal_sep_dim
      \l__xchoices_label_hsep_init_tl
    \dim_use:N \l__xchoices_coffin_join_horizontal_sep_dim
  }
\__xchoices_label_hsep_init:N
  \l__xchoices_coffin_current_label_pos_str
% \dim_use:N \l__xchoices_coffin_join_horizontal_sep_dim
\ExplSyntaxOff
\end{document}
```

**Comment by xkwxdyy** [comment]
不过我还是没采用上面的办法，还是采用了keys的inital来设置，因为我发现初值在keys里设置就不会溢出，
```tex
\cs_new:cpn { __xchoices_label_pos_set_left:NNN } #1#2#3
  {
    \dim_compare:nNnTF {#3} > { \baselineskip }
      {
        \coffin_join:NnnNnnnn
        #1 { H } { r }
        #2 { vc } { l }
        { 5pt + \l__xchoices_coffin_join_horizontal_sep_dim }     % 原来的
        { 0pt + \l__xchoices_coffin_join_horizontal_sep_dim }     % 现在的 + keys的label-hsep（就是 \l__xchoices_coffin_join_horizontal_sep_dim的设置）的inital=5pt就不会溢出
        { 2pt + \l__xchoices_coffin_join_vertical_sep_dim }
      }
...
```
但是如果像上面那样通过`\__xchoices_label_hsep_init:N`的方式来定义初始值，和coffin里用5pt效果一样，都会溢出，很神奇...我不太明白道理。

然后`right`系列的只能变通一下, 在coffin的设置里改成
```tex
\coffin_join:NnnNnnnn
        #1 { ... } { ... }
        #2 { ... } { ... }
        { -10pt + \l__xchoices_coffin_join_horizontal_sep_dim }   
```
`-10`一个是为了抵消掉`\l__xchoices_coffin_join_horizontal_sep_dim `的inital的5pt
其次是`varwidth`的宽度里其实减掉了`\l__xchoices_coffin_join_horizontal_sep_dim `，所以宽度小了，通过再往右移动的方式，最终`right`系列的对齐也没问题
![image](https://user-images.githubusercontent.com/87134063/152289644-ed4ddb55-f683-490a-93ae-2eae9130905b.png)

**Comment by zepinglee** [comment]
其实我觉得标签位置只需要配置左上、左中、下三个位置就够了，右边的很少见。

**Comment by xkwxdyy** [comment]
> 其实我觉得标签位置只需要配置左上、左中、下三个位置就够了，右边的很少见。

可能一些对称版面或者一些特殊的需要，比如小学的图好像很多是左边一个右边一个，我这个label-style可以设置为none，就算是单独拿来排那种居右的图也是不错的

**Comment by xkwxdyy** [comment]
@zepinglee https://github.com/xkwxdyy/xchoices/issues/4#issuecomment-1028615784
李老师上面提到的这个报错能麻烦看一下吗，我实在看不出是什么原因

**Comment by xkwxdyy** [comment]
> @zepinglee [#4 (comment)](https://github.com/xkwxdyy/xchoices/issues/4#issuecomment-1028615784) 李老师上面提到的这个报错能麻烦看一下吗，我实在看不出是什么原因

应该因为`\...if_in...`函数不可展开，使用case型可以解决：
```tex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
\dim_new:N \l__xchoices_coffin_join_horizontal_sep_dim
\str_new:N \l__xchoices_coffin_current_label_pos_str
\str_set:Nn \l__xchoices_coffin_current_label_pos_str {left}
\tl_new:N \l__xchoices_label_hsep_init_tl
\cs_generate_variant:Nn \dim_set:Nn {NV}
\cs_new:Npn \__xchoices_label_hsep_init:N #1
  {
    \dim_set:Nn
      \l__xchoices_coffin_join_horizontal_sep_dim
      {
        \str_case:VnF #1
          {
            {left}{5pt}
            {right}{-5pt}
          }
          {0pt}
      }
    \dim_use:N \l__xchoices_coffin_join_horizontal_sep_dim
  }
\__xchoices_label_hsep_init:N
  \l__xchoices_coffin_current_label_pos_str
\ExplSyntaxOff
\end{document}
```

**Comment by zepinglee** [comment]
> @zepinglee [#4 (comment)](https://github.com/xkwxdyy/xchoices/issues/4#issuecomment-1028615784) 李老师上面提到的这个报错能麻烦看一下吗，我实在看不出是什么原因

似乎是 `\dim_set:Nn` 的 <dimexpr> 不支持 `\..if..:...TF` 之类的条件分支。我觉得把 `\dim_set:Nn` 放在分支内部更自然一些（类似别的很多编程语言）：
```latex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
\dim_new:N \l__xchoices_coffin_join_horizontal_sep_dim
\str_new:N \l__xchoices_coffin_current_label_pos_str
\str_set:Nn \l__xchoices_coffin_current_label_pos_str {left}
\cs_new:Npn \__xchoices_label_hsep_init:N #1
  {
    \str_if_in:NnTF #1 {left}
      { \dim_set:Nn \l__xchoices_coffin_join_horizontal_sep_dim { 5pt } }
      {
        \str_if_in:NnTF #1 {right}
          { \dim_set:Nn \l__xchoices_coffin_join_horizontal_sep_dim { -5pt } }
          { \dim_set:Nn \l__xchoices_coffin_join_horizontal_sep_dim { 0pt } }
      }
  }
\__xchoices_label_hsep_init:N \l__xchoices_coffin_current_label_pos_str
\dim_use:N \l__xchoices_coffin_join_horizontal_sep_dim
\ExplSyntaxOff
\end{document}
```

**Comment by xkwxdyy** [comment]
> 似乎是 \dim_set:Nn 的 不支持 \..if..:...TF 之类的条件分支。我觉得把 \dim_set:Nn 放在分支内部更自然一些（类似别的很多编程语言）：

了解，谢谢李老师
